# Generated by Django 4.2.7 on 2023-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_address',
            field=models.CharField(max_length=50),
        ),
    ]
